### ISSUE TITLE
Edit Tasks

### ISSUE THREAD

**Issue by johnnywell** [LucasEduardoGiovanini/clean-python-todo-list#2]
It would be nice if I could just edit a task from a list, instead of having to delete it and create a new one.

**Comment by LucasEduardoGiovanini** [comment]
I can't believe I forgot that...

**Comment by johnnywell** [comment]
It's not what I was talking about. I hope you'll notice the problem when doing this feature, but that is not what is missing. It's something more fundamental.

**Comment by LucasEduardoGiovanini** [comment]
I also need to implement editing the list name.

**Comment by johnnywell** [comment]
You need to learn how to link the issues to the PR, so they are closed when the PR is accepted.

**Comment by LucasEduardoGiovanini** [comment]
You're right, I'll do it next time.
As the PR has already been done, can I close this issue myself?

**Comment by johnnywell** [comment]
sure
